export const projects = [
  {
    id: "bewear-ecommerce",
    name: "BeWear E-commerce",
    image_path: "/bewear-store.png",
    technologies: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Node.js",
      "Express",
      "PostgreSQL",
      "Drizzle ORM",
      "Better Auth",
      "Vercel",
      "Git",
    ],
    link: "https://store.kaycfarias.dev/",
    repo_url: "https://github.com/Kaycfarias/ecommerce-bewear",
  },
  {
    id: "http-client",
    name: "HTTP Client",
    image_path: "/http-client.png",
    technologies: ["Rust", "Iced", "Reqwest", "Tokio", "Cargo", "Git"],
    link: "https://github.com/Kaycfarias/http-client",
    repo_url: "https://github.com/Kaycfarias/http-client",
  },
  {
    id: "portfolio-website",
    name: "Portfolio Website",
    image_path: "/portifolio-site.png",
    technologies: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "ShadCN UI",
      "Styled Components",
      "Framer Motion",
      "React",
      "Vercel",
      "Git",
    ],
    link: "https://kaycfarias.dev/",
    repo_url: "https://github.com/Kaycfarias/portifolio-2",
  },
];
